# this file was generated by inspectdb
from django.db import models


class User(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    username = models.CharField(db_column='USERNAME', max_length=45)
    email = models.CharField(db_column='EMAIL', max_length=100)
    password = models.CharField(db_column='PASSWORD', max_length=45)

    class Meta:
        managed = True
        db_table = 'USER'


class Tweet(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    user = models.ForeignKey('User', models.DO_NOTHING, db_column='USER_ID')
    content = models.CharField(db_column='CONTENT', max_length=45)
    timestamp = models.DateTimeField(db_column='TIMESTAMP')
    like_counter = models.IntegerField(db_column='LIKE_COUNTER')
    parent_tweet = models.ForeignKey('self', models.DO_NOTHING, db_column='PARENT_TWEET', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'TWEET'


class Follow(models.Model):
    user = models.ForeignKey('User', models.DO_NOTHING, db_column='USER_ID')
    follow_id = models.IntegerField(db_column='FOLLOW_ID')
    is_following = models.CharField(db_column='IS_FOLLOWING', max_length=1)

    class Meta:
        managed = True
        db_table = 'FOLLOW'


class Likes(models.Model):
    tweet = models.ForeignKey('Tweet', models.DO_NOTHING, db_column='TWEET_ID')
    user = models.ForeignKey('User', models.DO_NOTHING, db_column='USER_ID')
    timestamp = models.DateTimeField(db_column='TIMESTAMP')

    class Meta:
        managed = True
        db_table = 'LIKES'
