# Generated by Django 2.1.5 on 2019-02-08 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_id', models.IntegerField(db_column='FOLLOW_ID')),
                ('is_following', models.CharField(db_column='IS_FOLLOWING', max_length=1)),
            ],
            options={
                'db_table': 'FOLLOW',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_column='TIMESTAMP')),
            ],
            options={
                'db_table': 'LIKES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('content', models.CharField(db_column='CONTENT', max_length=45)),
                ('timestamp', models.DateTimeField(db_column='TIMESTAMP')),
                ('like_counter', models.IntegerField(db_column='LIKE_COUNTER')),
                ('parent_tweet', models.ForeignKey(blank=True, db_column='PARENT_TWEET', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Tweet')),
            ],
            options={
                'db_table': 'TWEET',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='USERNAME', max_length=45)),
                ('email', models.CharField(db_column='EMAIL', max_length=100)),
                ('password', models.CharField(db_column='PASSWORD', max_length=45)),
            ],
            options={
                'db_table': 'USER',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.User'),
        ),
        migrations.AddField(
            model_name='likes',
            name='tweet',
            field=models.ForeignKey(db_column='TWEET_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.Tweet'),
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.User'),
        ),
    ]
